name: Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: yarn add vercel

      - name: Deploy
        run: yarn build && vercel -c --token ${{secrets.ZEIT_TOKEN}}
