name: Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: yarn add vercel

      - name: Build
        run: yarn build

      - name: Deploy
        run: vercel -c --prod --token ${{ secrets.VERCEL_TOKEN }}
